defaults:
  - _self_
  - env
  - uav

renderMode: "human"  # 渲染模式
# renderMode: None  # 渲染模式
device: "cuda:0"  # 训练设备

# 训练参数
actionBound: 2.0  # 动作限制
bufferSize: 5000  # 经验回放池容量
minimalSize: 32  # 经验回放池的最小启用容量
batchSize: 32  # 批次大小
navigationModel: "SAC"  # 模型种类
# navigationModel: "DDPG"
retrain: True  # 是否重新训练
numEpisodes: 5000  # 训练轮次
seed: 0  # 随机种子